name: Process Excel to CSV
on:
  push:
    paths:
      - 'DMS_Input.xlsx'
  workflow_dispatch: # Cho phép nhấn nút chạy thủ công trên GitHub

jobs:
  convert_to_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v4

      - name: Cài đặt Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Cài đặt thư viện
        run: |
          pip install pandas openpyxl msal requests

      - name: Chạy Script xử lý file
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: python extract_data.py
